Foodtruck/Controllers/ActualitésController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodtruckData;

namespace Foodtruck.Controllers
{
    public class ActualitésController : Controller
    {
        private FoodTruckEntities db = new FoodTruckEntities();

        // GET: Actualités
        public ActionResult Index()
        {
            return View(db.Actualités.ToList());
        }

        // GET: Actualités/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actualités actualités = db.Actualités.Find(id);
            if (actualités == null)
            {
                return HttpNotFound();
            }
            return View(actualités);
        }

        // GET: Actualités/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actualités/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_actualite,titre,description,image")] Actualités actualités)
        {
            if (ModelState.IsValid)
            {
                db.Actualités.Add(actualités);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(actualités);
        }

        // GET: Actualités/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actualités actualités = db.Actualités.Find(id);
            if (actualités == null)
            {
                return HttpNotFound();
            }
            return View(actualités);
        }

        // POST: Actualités/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_actualite,titre,description,image")] Actualités actualités)
        {
            if (ModelState.IsValid)
            {
                db.Entry(actualités).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(actualités);
        }

        // GET: Actualités/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actualités actualités = db.Actualités.Find(id);
            if (actualités == null)
            {
                return HttpNotFound();
            }
            return View(actualités);
        }

        // POST: Actualités/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Actualités actualités = db.Actualités.Find(id);
            db.Actualités.Remove(actualités);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Foodtruck/Controllers/HomeController.cs
using Foodtruck.Models;
using FoodtruckData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Foodtruck.Controllers
{
    public class HomeController : Controller
    {

        private FoodTruckEntities db = new FoodTruckEntities();

        public ActionResult Index()
        {
            var listActu = db.Actualités.ToList();

            var prodSucces = db.Produits.OrderBy(f => f.stock>0).Take(3).ToList();

            ActualitesTopProd dto = new ActualitesTopProd
            {
                Actus = listActu,
                Prod = prodSucces
            };


            return View(dto);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Foodtruck/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodtruckData;

namespace Foodtruck.Controllers
{
    public class ProduitsController : Controller
    {
        private FoodTruckEntities db = new FoodTruckEntities();

        // GET: Produits
        public ActionResult Index()
        {
            var produits = db.Produits.Include(p => p.Famille_repas).Include(p => p.Ligne_commande);
            return View(produits.ToList());
        }

        // GET: Produits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produits produits = db.Produits.Find(id);
            if (produits == null)
            {
                return HttpNotFound();
            }
            return View(produits);
        }

        // GET: Produits/Create
        public ActionResult Create()
        {
            ViewBag.id_produit = new SelectList(db.Famille_repas, "id_famille_repas", "libelle");
            ViewBag.id_produit = new SelectList(db.Ligne_commande, "id_ligne_commande", "id_ligne_commande");
            return View();
        }

        // POST: Produits/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_produit,libelle_commercial,libelle_technique,description,stock,prix_unitaire,id_famille_repas")] Produits produits)
        {
            if (ModelState.IsValid)
            {
                db.Produits.Add(produits);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_produit = new SelectList(db.Famille_repas, "id_famille_repas", "libelle", produits.id_produit);
            ViewBag.id_produit = new SelectList(db.Ligne_commande, "id_ligne_commande", "id_ligne_commande", produits.id_produit);
            return View(produits);
        }

        // GET: Produits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produits produits = db.Produits.Find(id);
            if (produits == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_produit = new SelectList(db.Famille_repas, "id_famille_repas", "libelle", produits.id_produit);
            ViewBag.id_produit = new SelectList(db.Ligne_commande, "id_ligne_commande", "id_ligne_commande", produits.id_produit);
            return View(produits);
        }

        // POST: Produits/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_produit,libelle_commercial,libelle_technique,description,stock,prix_unitaire,id_famille_repas")] Produits produits)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produits).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_produit = new SelectList(db.Famille_repas, "id_famille_repas", "libelle", produits.id_produit);
            ViewBag.id_produit = new SelectList(db.Ligne_commande, "id_ligne_commande", "id_ligne_commande", produits.id_produit);
            return View(produits);
        }

        // GET: Produits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produits produits = db.Produits.Find(id);
            if (produits == null)
            {
                return HttpNotFound();
            }
            return View(produits);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produits produits = db.Produits.Find(id);
            db.Produits.Remove(produits);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Foodtruck/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Foodtruck/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Foodtruck/Views/Home/Index.cshtml
@model Foodtruck.Models.ActualitesTopProd
@{
    ViewBag.Title = "Home Page";
}




    <div class=" container-fluid containerHome">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <a href=" @Url.Action("Details","Actualités",new {id =Model.Actus[0].id_actualite })">
                        <img src="~/Ressources/@Model.Actus[0].image" class="d-block w-100" alt="...">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h5>@Model.Actus[0].titre</h5>

                    </div>

                </div>
                @for (int i = 1; i < Model.Actus.Count; i++)
                {
                    <div class="carousel-item">
                        <a href=" @Url.Action("Details","Actualités",new {id =Model.Actus[i].id_actualite })" >
                            <img src="~/Ressources/@Model.Actus[i].image" class="d-block w-100" alt="...">
                        </a>
                       
                        <div class="carousel-caption d-none d-md-block">
                            <h5>@Model.Actus[i].titre</h5>

                        </div>

                    </div>

                }
            </div>

        </div>
        <h1>Nos produits phares !</h1>
        @foreach (FoodtruckData.Produits prod in Model.Prod)
        {
            <article class="info-block col-md-3 col-sm-6">
                <h4>
                    @Html.ActionLink(prod.libelle_commercial, "Details", "Produits", new { id = prod.id_produit }, new { @class = "lien-formation" })
                </h4>

                <p>@prod.description</p>
            </article>
        }

    </div>